// Copyright 2022 Pratik R Gupte. See repository licence in LICENSE.md.
// Generated by using Rcpp::compileAttributes() and manually modified

#ifndef testclasslinking_testclasslinking_H_
#define testclasslinking_testclasslinking_H_

#include <Rcpp.h>

#include "class.h"

#endif  // testclasslinking_testclasslinking_H_

// Undef FALSE which may be defined as integer in one of the imported third
// party headers.
// This solution copied from https://github.com/RcppCore/Rcpp/issues/846
#ifdef FALSE
#undef FALSE
#endif
