// Copyright 2022 Pratik R Gupte. See repository licence in LICENSE.md.
// Generated by using Rcpp::compileAttributes() and manually modified

#ifndef testclasslinking_testclasslinking_H_
#define testclasslinking_testclasslinking_H_

#include <Rcpp.h>

#include "class.h"

#endif  // testclasslinking_testclasslinking_H_
