# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_numbers <- function(samples, multithreaded = FALSE) {
    .Call(`_testclasslinking_get_numbers`, samples, multithreaded)
}

get_numbers_vec <- function(samples) {
    .Call(`_testclasslinking_get_numbers_vec`, samples)
}

get_numbers_func <- function(list) {
    .Call(`_testclasslinking_get_numbers_func`, list)
}

